on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check
        run: nix flake check
      - uses: DeterminateSystems/magic-nix-cache-action@main
